# Generated by Django 5.2.5 on 2025-08-21 06:35

import django.core.validators
import webgame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('zip_file', models.FileField(blank=True, help_text='Upload a ZIP file containing your game build', null=True, upload_to=webgame.models.game_upload_path, validators=[webgame.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('extracted_path', models.CharField(blank=True, help_text='Auto-filled path to extracted index.html', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Optional URL to the game if hosted externally', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
