# Generated by Django 5.2.5 on 2025-08-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
        ('webgame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webgame',
            name='author',
            field=models.ForeignKey(default=1, help_text='The user who uploaded the game', on_delete=django.db.models.deletion.CASCADE, related_name='webgames', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webgame',
            name='reactions',
            field=models.ManyToManyField(blank=True, help_text='Users who reacted to the game', related_name='webgame_reactions', to='blog.reaction'),
        ),
    ]
