# Generated by Django 5.2.5 on 2025-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0002_webgame_author_webgame_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgame',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this game has been approved'),
        ),
    ]
