# Generated by Django 5.2.5 on 2025-08-21 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_published'),
        ('webgame', '0003_webgame_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='webgame',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webgames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webgame',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webgame',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='webgames', to='blog.reaction'),
        ),
    ]
