# Generated by Django 5.2.5 on 2025-08-21 08:29

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0004_alter_webgame_options_alter_webgame_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgame',
            name='extracted_path',
            field=models.FilePathField(blank=True, help_text='Auto-filled path to extracted index.html', match='.*index\\.html$', path=pathlib.PureWindowsPath('E:/Projects/Slog/media/games/djangodbmodelsfieldscharfield')),
        ),
    ]
