# Generated by Django 5.2.5 on 2025-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0005_alter_webgame_extracted_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgame',
            name='extracted_path',
            field=models.FileField(blank=True, help_text='Auto-filled path to extracted index.html', upload_to=''),
        ),
    ]
