# Generated by Django 5.2.5 on 2025-08-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0006_alter_webgame_extracted_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webgame',
            name='reactions',
        ),
    ]
