# Generated by Django 5.2.5 on 2025-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_id_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, help_text='GitHub user ID', max_length=255, null=True, unique=True),
        ),
    ]
