# Generated by Django 5.2.5 on 2025-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], help_text='Email visibility', max_length=255, null=True),
        ),
    ]
