# Generated by Django 5.2.5 on 2025-08-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useremails_visibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmails',
        ),
    ]
