# Generated by Django 5.2.4 on 2025-08-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Slug for the tag', unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], help_text='Type of reaction', max_length=10)),
                ('user', models.ForeignKey(help_text='User who made the reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=255)),
                ('slug', models.SlugField(help_text='Slug for the blog post', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Content of the blog post')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date and time of the post')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date and time of the post')),
                ('author', models.ForeignKey(blank=True, help_text='Author of the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, help_text='Reactions to the post', related_name='posts', to='blog.reaction')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the post', related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date and time of the comment')),
                ('author', models.ForeignKey(help_text='Author of the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(help_text='Post that the comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('reactions', models.ManyToManyField(blank=True, help_text='Reactions to the comment', related_name='comments', to='blog.reaction')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
