# Generated by Django 5.2.5 on 2025-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reaction_comment_post_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', help_text='Slug for the blog post', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
