# Generated by Django 5.2.5 on 2025-08-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_published'),
        ('webgame', '0007_remove_webgame_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='webgame',
            field=models.ForeignKey(blank=True, help_text='Web game associated with the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='webgame.webgame'),
        ),
    ]
