# Generated by Django 5.2.5 on 2025-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, help_text='Reactions to the post', null=True, related_name='posts', to='blog.reaction'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with the post', null=True, related_name='posts', to='blog.tag'),
        ),
    ]
